name: dealmart
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  flutter_webview_plugin: ^0.3.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intro_slider: ^2.3.1
  flutter_spinkit: ^4.0.0
  smooth_star_rating: ^1.1.1
  carousel_slider: ^1.3.0
  firebase_analytics:
  firebase_core:
  custom_switch: ^0.0.1
  connectivity:
  rxdart: 0.20.0
  http: ^0.12.1
  flutter_icons: ^1.1.0
  xs_progress_hud: ^1.0.2
  firebase_messaging:
  flutter_statusbarcolor: ^0.2.3
  firebase_auth: ^0.16.0
  firebase_database:
  localize_and_translate:
  shared_preferences: ^0.5.4+5
  flutter_slidable: ^0.5.7
  percent_indicator: ^2.1.5
  google_maps_flutter: ^0.5.19+2
  location: ^2.3.5
  geolocator: ^5.3.1
  pin_code_fields: ^3.0.0
  geocoder: ^0.2.1
  image_stack: ^1.1.0
  flutter_facebook_login: ^3.0.0
  toast: ^0.1.5
  image_picker: ^0.6.0+10
  dio: ^3.0.10
  flutter_svg: ^0.19.0
  google_sign_in:
  share:
  better_player: ^0.0.23
  permission_handler: ^5.0.1+1
  flutter_inappwebview: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/langs/ar.json
    - assets/langs/en.json
    - images/girleImage.png
    - images/icons_google.png
    - images/car_test.png
    - images/contact_image.png
    - images/coins_icon.png
    - images/earth_icon.png
    - images/favorate_icon.png
    - images/settings_icon.png
    - images/ads.png
    - images/free_delivery.png
    - images/card.png
    - images/noData.png
    - images/zcash.png
    - images/wallet.jpeg
    - images/fawery.png
    - images/credit.png
    - images/logOutImage.jpeg


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
